import type { Metadata } from "next";
import { Geist, Geist_Mono, Lusitana } from "next/font/google";
import "./globals.css";

const lusitana = Lusitana({
  variable: "--font-lusitana",
  subsets: ['latin'],
  weight: ['400', '700'], // según los pesos que necesites
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lusitana.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
